services:
  - type: web
    name: taskapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    env: production
    region: oregon
    dependsOn:
      - taskapp_postgres
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskapp_postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
    healthCheckPath: /up
    autoDeploy: true

databases:
  - name: taskapp_postgres
    plan: free
    postgresMajorVersion: 15